spring:
  application:
    name: facturation-service

  datasource:
    url: jdbc:postgresql://localhost:5432/facturation_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083